[pytest]
cache_dir = runtimes/cache/pytest
addopts = --basetemp=runtimes/cache/pytest-tmp
testpaths = app/tests/unit app/tests/e2e
norecursedirs = .git .tox .nox .eggs *.egg node_modules dist build runtimes assets .*
