from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from server.contracts.training import ResumeConfig, TrainingSettings

ROOT_DIR = Path(__file__).resolve().parents[2]
OUTPUT_PATH = ROOT_DIR / "app" / "client" / "src" / "generated" / "trainingDefaults.ts"


def _model_defaults(model_fields: dict[str, Any], names: set[str] | None = None) -> dict[str, Any]:
    selected = names if names is not None else set(model_fields)
    return {
        name: model_fields[name].get_default(call_default_factory=True)
        for name in sorted(selected)
    }


def _render() -> str:
    training_payload = json.dumps(
        _model_defaults(TrainingSettings.model_fields),
        indent=4,
        sort_keys=True,
    )
    resume_payload = json.dumps(
        _model_defaults(ResumeConfig.model_fields, {"additional_episodes"}),
        indent=4,
        sort_keys=True,
    )
    return (
        "// Generated by app/scripts/export_training_defaults.py. Do not edit manually.\n"
        f"export const TRAINING_DEFAULTS = {training_payload} as const;\n\n"
        f"export const RESUME_DEFAULTS = {resume_payload} as const;\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if checked-in frontend defaults differ from backend contracts.",
    )
    args = parser.parse_args()

    expected = _render()
    if args.check:
        if not OUTPUT_PATH.is_file() or OUTPUT_PATH.read_text(encoding="utf-8") != expected:
            raise SystemExit(
                "Frontend training defaults are stale. Run "
                "`uv --project app/server run python app/scripts/export_training_defaults.py`."
            )
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
