from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from server.contracts.training import TrainingSettings

ROOT_DIR = Path(__file__).resolve().parents[2]
OUTPUT_PATH = ROOT_DIR / "app" / "client" / "src" / "generated" / "trainingDefaults.ts"


def _training_defaults() -> dict[str, Any]:
    defaults: dict[str, Any] = {}
    for name, field in TrainingSettings.model_fields.items():
        defaults[name] = field.get_default(call_default_factory=True)
    return defaults


def _render() -> str:
    payload = json.dumps(_training_defaults(), indent=4, sort_keys=True)
    return (
        "// Generated by app/scripts/export_training_defaults.py. Do not edit manually.\n"
        f"export const TRAINING_DEFAULTS = {payload} as const;\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if the checked-in frontend defaults differ from TrainingSettings.",
    )
    args = parser.parse_args()

    expected = _render()
    if args.check:
        if not OUTPUT_PATH.is_file() or OUTPUT_PATH.read_text(encoding="utf-8") != expected:
            raise SystemExit(
                "Frontend training defaults are stale. Run "
                "`uv --project app/server run python app/scripts/export_training_defaults.py`."
            )
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
